# Generated by Django 3.2.5 on 2021-08-06 00:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=20)),
                ('content_type', models.CharField(choices=[('한국영화', '한국영화'), ('외국영화', '외국영화'), ('자유글', '자유글')], default='----', max_length=20)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('board_hit', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
