# Generated by Django 3.2.5 on 2021-08-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_board_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='file_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
