# Generated by Django 3.2.5 on 2021-08-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('pub_date', models.DateField()),
                ('director', models.CharField(max_length=100)),
            ],
        ),
    ]
