# Generated by Django 3.2.5 on 2021-08-11 01:06

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='movie',
            name='like_user',
            field=models.ManyToManyField(related_name='like_movie', to=settings.AUTH_USER_MODEL),
        ),
    ]
